<?php
/**
 * Created by PhpStorm.
 * User: ADMIN
 * Date: 2019/9/5
 * Time: 16:05
 */
namespace app\common\controller;

use think\facade\Session;

class Server extends Base{

    /**
     * 免登录节点
     * @var array
     */
    private $accessWithoutLogin = [
        'login.index','login.login','authorize.authorizetoken','authorize.authorizeuserinfo'
    ];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //判断登录
        $node = strtolower($this->request->controller() . '.' . $this->request->action());
        if(!in_array($node,$this->accessWithoutLogin) && empty($this->userInfo())){
            $redirect_url = urlencode($this->request->url());
            $this->redirect('/login/index?redirect_url=' . $redirect_url);
        }
    }

    public function userInfo($attr = ''){
        $userinfo = Session::get("USER_INFO");
        return $attr ? (isset($userinfo[$attr]) ? $userinfo[$attr] : '') : $userinfo;
    }

    public function setUserInfo($user){
        Session::set("USER_INFO",$user);
        return $user;
    }


}